#!/bin/bash
#       | |_| |_ ___
#       | __| __/ __|
#       | |_| |_\__ \
#        \__|\__|___|
# https://github.com/galaxey-cli/tts
# tts - Simple text-to-speech utility using Festival and optional GPT integration

sudo apt update
sudo apt install -y festival xsel git

# Check if tgpt directory exists before cloning and installing
if [ -d tgpt ]; then
    echo "tgpt is already installed (directory exists). Skipping clone and install."
else
    git clone https://github.com/aandrew-me/tgpt.git
    sh tgpt/install
fi
